apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-pipeline-scheduledworkflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-runner
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyter
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyter-notebook
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-ui
  namespace: kubeflow
